export default [
    {
        ignores: ["frontend/vendor/**"],
    },
    {
        files: ["frontend/**/*.js"],
        ignores: ["frontend/sw.js"],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "script",
            globals: {
                window: "readonly",
                document: "readonly",
                localStorage: "readonly",
                navigator: "readonly",
                crypto: "readonly",
                console: "readonly",
                WebSocket: "readonly",
                TextEncoder: "readonly",
                TextDecoder: "readonly",
                Uint8Array: "readonly",
                DataView: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                Vue: "readonly",
                ecutils: "readonly",
                Protocol: "readonly",
                indexedDB: "readonly",
                Blob: "readonly",
                URL: "readonly",
                FileReader: "readonly",
                Notification: "readonly",
                Worker: "readonly",
                location: "readonly",
            },
        },
        rules: {
            "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
            "no-undef": "error",
            "no-constant-condition": "off",
            "eqeqeq": ["error", "always"],
            "no-var": "error",
            "prefer-const": "warn",
            "no-eval": "error",
            "no-implied-eval": "error",
            "no-new-func": "error",
        },
    },
    {
        files: ["frontend/sw.js"],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "script",
            globals: {
                self: "readonly",
                caches: "readonly",
                fetch: "readonly",
                URL: "readonly",
                console: "readonly",
                Response: "readonly",
            },
        },
        rules: {
            "no-undef": "error",
            "no-var": "error",
            "prefer-const": "warn",
        },
    },
];
